```{r}
source("CD_Processing.R")
source("LineageProcessing.R")
library("plotly")
```
```{r}
dat15 <- CD_In(directory = "JIM767_15Corrected/", AuxInfo = F, TIME = "corrected", prefix = "")|>
  Emb_drop(dropEmb = "20240904_JIM767_L1") |>
  trimCD(c("none", 'global', 'gweight', 'size','cellTime', 'z', 'x', 'y'))
dat25 <- CD_In(directory = "JIM767_25Corrected/", AuxInfo = F, TIME = "corrected", prefix = "")|>
  trimCD(c("none", 'global', 'gweight', 'size','cellTime', 'z', 'x', 'y'))
datControl <- CD_In(directory = "JIM767_ControlCorrected/", AuxInfo = F, TIME = "corrected", prefix = "")|> trimCD(c("none", 'global', 'gweight', 'size', 'cellTime', 'z', 'x', 'y'))
```
```{r}
lineExp <- strsplit("ABal, ABalp, ABalpa, ABalpaa, ABalpaaa, ABalpaaaa, ABalpaaaaa", split=", ")[[1]]
lineAll <- c("ABalp", "ABara", "ABplpappp", "ABprpappp")
```
```{r}
library(viridis)
names15 <- names(dat15[["CD"]])
emb_palette15 <- turbo(length(names15)) |> setNames(names15)
names25 <- names(dat25[["CD"]])
emb_palette25 <- turbo(length(names25)) |> setNames(names25)
namesC <- names(datControl[["CD"]])
emb_paletteC <- turbo(length(namesC)) |> setNames(namesC)
```
```{r}
yrange = list(0,16000)
xrange = list(-50,300)
fig15All <- dat15|>plotBlotLine(title = '15deg All AB', 
                            aligningCell = lineAll[1], alignTime = 0, lineages = lineAll, 
                            color_palette = emb_palette15,
                            xrange = xrange, yrange = yrange)
fig15line <- dat15|>plotBlotLine(title = '15deg sublineage example', 
                            aligningCell = lineExp[2], alignTime = 0, cells = lineExp, 
                            color_palette = emb_palette15,
                            xrange = xrange, yrange = yrange)
```
```{r}
fig25All <- dat25|>plotBlotLine(title = '25deg All AB', 
                            aligningCell = lineAll[1], alignTime = 0, lineages = lineAll, 
                            color_palette = emb_palette25,
                            xrange = xrange, yrange = yrange)

fig25line <- dat25|>plotBlotLine(title = '25deg sublineage example', 
                            aligningCell = lineExp[2], alignTime = 0, cells = lineExp, 
                            color_palette = emb_palette25,
                            xrange = xrange, yrange = yrange)
```
```{r}
figControlAll <- datControl|>plotBlotLine(title = 'Control All AB', 
                            aligningCell = lineAll[1], alignTime = 0, lineages = lineAll, 
                            color_palette = emb_paletteC,
                            xrange = xrange, yrange = yrange)

figControlline <- datControl|>plotBlotLine(title = 'Control sublineage example', 
                            aligningCell = lineExp[2], alignTime = 0, cells = lineExp, 
                            color_palette = emb_paletteC,
                            xrange = xrange, yrange = yrange)
```
```{r}
figCombine <- subplot(fig15line, fig15All, fig25line, fig25All, figControlline, figControlAll,
                      nrows = 3,
                      shareX=T, shareY=T, titleX = T, titleY = T)|>
  layout(title = 'pha-4 expression, Sublineage example is ABprpappp', showlegend=F)
figCombine
```
```{r}
fig15II <- dat15|>plotBlotLine(title = '15deg All AB', 
                            aligningCell = lineAll[1], alignTime = "NO", lineages = lineAll, 
                            color_palette = emb_palette15,
                            xrange = xrange, yrange = yrange)
```
```{r}
fig15II
```
```{r}
fig15All
```

